spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      accessKey: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      secretKey: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
    region:
      static: ap-northeast-2
    stack:
      auto-: false